Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0567f647e75c7bc05
      KeyName: ariesbabu-nutanix
      SecurityGroupIds:
      - sg-d9875793
  MyEP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MyInstance
