apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: metal-lb-ip-space
      protocol: layer2
      addresses:
      - 10.x.x.x-10.x.x.x
